from __future__ import annotations

import os
import shutil
import tempfile
import unittest
import warnings

from context import dpdata

from dpdata.formats.vasp.outcar import (
    check_potcar_poscar_order,
    formula_from_poscar_title,
)

SOURCE = os.path.join("poscars", "OUTCAR.ch4.1step")


class TestPoscarTitleFormula(unittest.TestCase):
    """The POSCAR title is free-form text and only sometimes a formula."""

    def test_formula_with_counts(self):
        self.assertEqual(
            formula_from_poscar_title(" Li3 F39 K3 Mg3 Ca3 Na3 Al10 O6"),
            ["Li", "F", "K", "Mg", "Ca", "Na", "Al", "O"],
        )

    def test_formula_without_counts(self):
        self.assertEqual(formula_from_poscar_title("  H  C  "), ["H", "C"])

    def test_prose_is_not_a_formula(self):
        for title in (
            " POSCAR file written by OVITO",
            " File generated by python recompute scrip",
            " generated by SeeK-path",
        ):
            with self.subTest(title=title):
                self.assertIsNone(formula_from_poscar_title(title))

    def test_unknown_symbol_is_rejected(self):
        self.assertIsNone(formula_from_poscar_title(" Xx2 Yy3"))

    def test_single_token_is_rejected(self):
        # One species cannot disagree on ordering, and a one-word title is far
        # more likely to be prose.
        self.assertIsNone(formula_from_poscar_title(" Si"))

    def test_truncated_title_drops_the_cut_token(self):
        # VASP pads the title to 40 characters, cutting the last species.
        title = " Cr3 Mn5 Fe3 Co1 Ni4 Cu4 Zn2 Y5 Zr4 Nb5 M"
        self.assertEqual(
            formula_from_poscar_title(title),
            ["Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Y", "Zr", "Nb"],
        )


class TestPotcarPoscarOrderCheck(unittest.TestCase):
    def _warnings(self, atom_names, title):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            check_potcar_poscar_order(atom_names, title)
        return [str(ii.message) for ii in caught]

    def test_matching_order_is_silent(self):
        self.assertEqual(self._warnings(["H", "C"], "  H  C"), [])

    def test_missing_title_is_silent(self):
        self.assertEqual(self._warnings(["H", "C"], None), [])

    def test_prose_title_is_silent(self):
        self.assertEqual(
            self._warnings(["O", "H"], " POSCAR file written by OVITO"), []
        )

    def test_conflicting_order_warns(self):
        messages = self._warnings(
            ["Li", "O", "F"],
            " Li3 F39 K3",
        )
        self.assertEqual(len(messages), 1)
        self.assertIn("does not match the POSCAR title", messages[0])
        self.assertIn("Li O F", messages[0])
        self.assertIn("Li F K", messages[0])

    def test_truncated_title_compares_only_shared_species(self):
        # Only the species the title still carries may be compared.
        self.assertEqual(self._warnings(["Cr", "Mn", "Fe"], " Cr3 Mn5"), [])


class TestOutcarOrderMismatch(unittest.TestCase):
    """End-to-end: an OUTCAR whose POTCAR order contradicts its POSCAR title."""

    def setUp(self):
        with open(SOURCE) as fp:
            self.lines = fp.read().split("\n")
        self.tmp_dir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmp_dir, ignore_errors=True)

    def _load(self, lines):
        path = os.path.join(self.tmp_dir, "OUTCAR")
        with open(path, "w") as fp:
            fp.write("\n".join(lines))
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter("always")
            system = dpdata.LabeledSystem(path, fmt="vasp/outcar")
        messages = [
            str(ii.message)
            for ii in caught
            if "POTCAR species order" in str(ii.message)
        ]
        return system, messages

    def test_consistent_outcar_is_silent(self):
        system, messages = self._load(self.lines)
        self.assertEqual(system.data["atom_names"], ["H", "C"])
        self.assertEqual(messages, [])

    def test_swapped_potcar_order_warns(self):
        # Swap the two TITEL records so the POTCAR order becomes C, H while
        # the POSCAR title still says H C.
        titel = [i for i, ll in enumerate(self.lines) if "TITEL" in ll]
        self.assertEqual(len(titel), 2)
        swapped = list(self.lines)
        swapped[titel[0]], swapped[titel[1]] = (
            self.lines[titel[1]],
            self.lines[titel[0]],
        )
        system, messages = self._load(swapped)
        # dpdata keeps reporting what VASP computed, but says the inputs
        # disagree.
        self.assertEqual(system.data["atom_names"], ["C", "H"])
        self.assertEqual(len(messages), 1)
        self.assertIn("does not match the POSCAR title", messages[0])


if __name__ == "__main__":
    unittest.main()
